#!/usr/bin/env ruby
# Reads a dump from the /v1/users/:user_id/contacts API calls and generates profiles from it
# You have to pipe this script to the 'mongo' command
#   Example: ./import-test-profiles test-dataset.json | mongo localhost/xingwall-development
require 'json'

filename = ARGV[0]

abort "Usage: #{$0} <filename>" unless filename

content = File.read(filename)
json = JSON.parse(content)

json['contacts']['users'].each do |user|
  print "db.profiles.insert({"
  print "userId: \"#{user['id']}\", "
  print "wants: #{(user['wants'] || '' ).inspect}, "
  print "haves: #{(user['haves'] || '').inspect}, "
  print "interests: #{(user['interests'] || '').inspect}, "
  print "web_profiles: {"
  print ((user['web_profiles'] || {}).keys.map do |profile|
    "#{profile.gsub('.', '_').inspect}: #{user['web_profiles'][profile].to_json}"
  end.join(','))
  print "},"
  print "displayName: \"#{user['display_name']}\", "
  print "photoUrls: { size_128x128: #{user['photo_urls']['size_128x128'].inspect}, size_256x256: #{user['photo_urls']['size_256x256'].inspect}}"
  puts "})"
end
